### ISSUE TITLE
Error: Cannot find module '@sentry/wizard'

### ISSUE THREAD

**Issue by SpellChucker** [getsentry/sentry-cordova#31]
I am trying to do a clean `cordova platform add android` with version `0.7.0` and am getting the following error when it tries to install `sentry-cordova`:

```
Failed to install 'sentry-cordova': Error: Cannot find module '@sentry/wizard'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/project/plugins/sentry-cordova/scripts/before_plugin_install_uninstall.js:2:18)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Cannot find module '@sentry/wizard'
```

**Comment by SpellChucker** [comment]
Nevermind...you can't just update the version manually in package.json you have to actually re-install and then it works.
