### ISSUE TITLE
Cannot run cordova run browser -- --live-reload

### ISSUE THREAD

**Issue by RaulTsc** [getsentry/sentry-cordova#63]
Hey guys.

When running `cordova run browser -- --live-reload`

I get

```
Error when parsing /Users/raul/src/er-prism-cordova/platforms/ios/EverReal/Plugins/sentry-cordova/Sentry.framework/Info.plist TypeError: Cannot read property 'nodeName' of null
    at Object.parse (/Users/raul/src/er-prism-cordova/node_modules/plist/lib/parse.js:45:27)
    at Patcher.<anonymous> (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:103:30)
    at Patcher.<anonymous> (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:45:16)
    at Array.forEach (<anonymous>)
    at Patcher.<anonymous> (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:43:12)
    at Array.forEach (<anonymous>)
    at Patcher.__forEachFile (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:39:20)
    at Patcher.fixATS (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:101:17)
    at Patcher.patch (/Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/utils/Patcher.js:119:10)
    at /Users/raul/src/er-prism-cordova/plugins/cordova-plugin-browsersync/lib/pluginHook.js:91:17
```

Sentry-cordova version: 0.10.0
Cordova version: 8.0.0

What other info do you need from me?

**Comment by HazAT** [comment]
Just tried it myself, works just fine.
This error seems also to be completely unrelated, what sense does it make that `run browser` uses `Sentry.framework/Info.plist` ?
Are you using the latest version of the `sentry-cordova`?

**Comment by RaulTsc** [comment]
Does not make a lot of sense indeed.

I'm using 0.10.0. I see that the latest version is 0.10.2, do you think that is the issue? I will try to update

Do you have any other suggestions to try to fix it? :)

**Comment by HazAT** [comment]
hmm maybe removing platform browser
`cordova platform rm browser` `cordova platform add browser`
