### ISSUE TITLE
ionic build error

### ISSUE THREAD

**Issue by letsila** [getsentry/sentry-cordova#95]
I just installed Sentry on my ionic 3 app following the online [docs](https://docs.sentry.io/platforms/javascript/ionic/). I got an error everytime I try to build the app with `ionic cordova prepare ios`. I installed sentry without the ionic wrapper as specified in the documentation. My configs:

- macOS Mojave
- ionic 3.9.2
- node 10.12.0

````
$ ionic cordova prepare ios --prod
> ionic-app-scripts build --prod --target cordova --platform ios
[15:40:04]  ionic-app-scripts 3.1.11
[15:40:04]  build prod started ...
[15:40:04]  clean started ...
[15:40:04]  clean finished in 14 ms
[15:40:04]  copy started ...
[15:40:05]  deeplinks started ...
[15:40:06]  deeplinks finished in 630 ms
[15:40:06]  ngc started ...
[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 25
            In ambient enum declarations member initializer must be constant expression.

      L24:  Fatal = "fatal",
      L25:  /** TODO */
      L26:  Error = "error",

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 27
            In ambient enum declarations member initializer must be constant expression.

      L26:  Error = "error",
      L27:  /** TODO */
      L28:  Warning = "warning",

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 29
            In ambient enum declarations member initializer must be constant expression.

      L28:  Warning = "warning",
      L29:  /** TODO */
      L30:  Log = "log",

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 31
            In ambient enum declarations member initializer must be constant expression.

      L30:  Log = "log",
      L31:  /** TODO */
      L32:  Info = "info",

            In ambient enum declarations member initializer must be constant expression.

      L32:  Info = "info",
[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 33
      L33:  /** TODO */
      L34:  Debug = "debug",

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 35
            In ambient enum declarations member initializer must be constant expression.

      L34:  Debug = "debug",
      L35:  /** TODO */
      L36:  Critical = "critical"

            In ambient enum declarations member initializer must be constant expression.

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 37
[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 187
      L36:      Critical = "critical"
      L38:  /** TODO */

            In ambient enum declarations member initializer must be constant expression.

     L186:  Unknown = "unknown",
     L187:  /** The event was skipped due to configuration or callbacks. */
     L188:  Skipped = "skipped",

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 189
            In ambient enum declarations member initializer must be constant expression.

     L188:  Skipped = "skipped",
     L189:  /** The event was sent to Sentry successfully. */
     L190:  Success = "success",

            In ambient enum declarations member initializer must be constant expression.
[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 191

     L190:  Success = "success",
     L191:  /** The client is currently rate limited and will try again later. */
     L192:  RateLimit = "rate_limit",

            In ambient enum declarations member initializer must be constant expression.

     L192:  RateLimit = "rate_limit",
[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 193
     L193:  /** The event could not be processed. */
     L194:  Invalid = "invalid",

            In ambient enum declarations member initializer must be constant expression.

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 195
     L194:  Invalid = "invalid",
     L195:  /** A server-side error ocurred during submission. */
     L196:  Failed = "failed"

[15:40:31]  typescript: node_modules/@sentry/types/dist/index.d.ts, line: 197
            In ambient enum declarations member initializer must be constant expression.

     L196:      Failed = "failed"
     L198:  export declare namespace Status {

[15:40:31]  ionic-app-script task: "build"
[15:40:31]  Error: Failed to transpile TypeScript
Error: Failed to transpile TypeScript
    at errorCheckProgram (/Volumes/TS-HFS/Mobile/shifteo/pos-lyria/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:119:39)
    at Object.<anonymous> (/Volumes/TS-HFS/Mobile/shifteo/pos-lyria/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:89:21)
    at step (/Volumes/TS-HFS/Mobile/shifteo/pos-lyria/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Volumes/TS-HFS/Mobile/shifteo/pos-lyria/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Volumes/TS-HFS/Mobile/shifteo/pos-lyria/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
[ERROR] An error occurred while running subprocess ionic-app-scripts.

        ionic-app-scripts build --prod --target cordova --platform ios exited with exit code
        1.

        Re-running this command with the --verbose flag may provide more information.
````

**Comment by letsila** [comment]
Actually I needed to update the version of typescript to ^2.4.0 in my project. This issue can be closed.
